[workspace]
members = ["adapter", "app", "entity", "port", "service"]
resolver = "3"

[workspace.dependencies]
entity = { path = "./entity" }
service = { path = "./service" }
port = { path = "./port" }
adapter = { path = "./adapter" }
