[package]
name = "adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
entity.workspace = true
port = { version = "0.1.0", path = "../port" }
sqlx = { version = "0.8.6", features = ["postgres", "sqlite"] }
